<?php

return [
    'ctrl' => [
    ],
    'columns' => [
        'aColumn' => [
            'l10n_cat' => 'text',
            'config' => [
            ],
        ],
        'bColumn' => [
            'l10n_cat' => 'media',
            'config' => [
            ],
        ],
    ],
];

?>
-----
<?php

return [
    'ctrl' => [],
    'columns' => [
        'aColumn' => [
            'config' => [
            ],
        ],
        'bColumn' => [
            'config' => [
            ],
        ],
    ],
];

?>
